name: freqgym
channels:
  - pytorch
  - conda-forge
# - defaults
dependencies:
# 1/5 req main
    - python>=3.7,<3.9
    - numpy
    - pandas
    - pip

    - aiohttp
    - SQLAlchemy
    - python-telegram-bot
    - arrow
    - cachetools
    - requests
    - urllib3
    - jsonschema
    - TA-Lib
    - tabulate
    - jinja2
    - blosc
    - sdnotify
    - fastapi
    - uvicorn
    - pyjwt
    - colorama
    - questionary
    - prompt-toolkit


    # ============================
    # 2/5 req dev

    - black
    - coveralls
    - flake8
    - mypy
    - pylint
    - pytest
    - pytest-asyncio
    - pytest-cov
    - pytest-mock
    - isort
    - nbconvert

    # ============================
    # 3/5 req hyperopt

    - scipy
    - scikit-learn
    - filelock
    - scikit-optimize
    - joblib
    - progressbar2
    # ============================
    # 4/5 req plot

    - plotly
    - jupyter

    - pip:
        - pycoingecko
        - py_find_1st
        - tables
        - pytest-random-order
        - ccxt
        - flake8-tidy-imports
    # ============================
    # 4/5 req baselines3
    - pytorch
    - cudatoolkit=11.3
    - tensorboardx

    - pip:
        - mpu
        - ta
        - freqtrade
        - stable-baselines3
        - sb3-contrib